# Custom values for the bitnami/clickhouse Helm chart

# Configure the main ClickHouse service
service:
  type: NodePort
  nodePorts:
    # Default HTTP port 8123 exposed on NodePort 30123
    http: 30123
    # Default TCP client port 9000 exposed on NodePort 30000
    client: 30000
  # If you need to expose ClickHouse Keeper (if enabled), configure its service here
  # keeper:
  #   service:
  #     type: NodePort
  #     nodePorts:
  #       client: 30218 # Default Keeper client port 2181 exposed on NodePort 30218

# Configure data persistence
persistence:
  enabled: true
  size: 50Gi # Request 10GB of storage for the data volume
  # storageClass: standard # Uncomment and specify your storage class if needed

# You can add other configurations here, e.g., resource limits, replicas, etc.
replicaCount: 1
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "4"
    memory: "16Gi"
