apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-feed-collect-cronjob
spec:
  schedule: "0,30 14-21 * * *" # Runs at :00 and :30 past the hour, for hours 14 through 21 UTC. Approximates 9:30 AM - 5:00 PM ET considering DST.
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
          - name: collector
            image: ghcr.io/karimquant/data-feed-collect:latest
            imagePullPolicy: Always

            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DATABASE
              value: "postgres"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"

            # Add resource requests/limits here if needed
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "10Gi"
                cpu: "4"
            # Add command/args if your container needs specific entrypoint overrides
            command: ["sh", "-c"]
            args: ["python data_feed_collect/collectors/yfinance_option_chain.py"]
          restartPolicy: OnFailure # Restart the container if it fails
