apiVersion: v1
kind: Pod
metadata:
  name: test-pod-for-debugging
spec:
  containers:
  - name: debug-container
    # Replace with the actual image name and tag you want to test
    image: your-image-name:latest
    # Keep the container running indefinitely for debugging
    command: ["tail"]
    args: ["-f", "/dev/null"]
    # Add resource requests/limits, probes, etc. as needed for your environment
    # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
